### ISSUE TITLE
method to search from another program

### ISSUE THREAD

**Issue by frido** [pvutov/armory#11]
Hi,

I am currently writing an offline deck parser and was in the process of creating a detailed unit viewer. Would you accept a feature that could send a search request over IPC (eg. tcp socket) to your armory app and show it there ?

![deckbrowser](https://cloud.githubusercontent.com/assets/1138654/23263733/6fc7ac96-f9df-11e6-9b34-2ab71edb1a84.PNG)

**Comment by pvutov** [comment]
Sure, I imagine it won't affect the standard use case.
I assume you've already written it? Just submit a pull request and I'll merge it, maybe with some changes [I'm thinking there should be a launch argument that disables the function, so that users who don't have the deck parser don't see the server status message].

If you haven't written it yet I wouldn't mind doing so myself either, but you'd have to wait a bit because I'm busy nowadays.

**Comment by frido** [comment]
Thanks, yes I have some sample code that I'll need to clean up, the status message was from the example, will send a pull request when that's done.
